import org.specs2._

class EulerSpec extends Specification { def is =
  "The Project Euler problems:"                                         ^ p^
  "If we list all the natural numbers below 10 that are multiples of 3 or 5, we get 3, 5, 6 and 9. The sum of these multiples is 23." ^
    "Find the sum of all the multiples of 3 or 5 below 1000."           ! e1^
                                                                        endp^
  "Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:" ^
  "1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ..."                              ^ bt^
    "By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms." ! e2^
                                                                        endp^
  "The prime factors of 13195 are 5, 7, 13 and 29." ^
    "What is the largest prime factor of the number 600851475143 ?"     ! e3^
                                                                        endp^
  "A palindromic number reads the same both ways. The largest palindrome made from the product of two 2-digit numbers is 9009 = 91 × 99." ^
    "Find the largest palindrome made from the product of two 3-digit numbers." ! e4^
                                                                        endp^
  "2520 is the smallest number that can be divided by each of the numbers from 1 to 10 without any remainder." ^
    "What is the smallest positive number that is evenly divisible by all of the numbers from 1 to 20?" ! e5^
                                                                        end

  import Euler._

  def e1 = euler1 === 233168
  def e2 = euler2 === 4613732
  def e3 = euler3 === 6857
  def e4 = euler4 === 906609
  def e5 = euler5 === 232792560

}
