import org.specs2._
import specification.Tags

class EulerSpec extends Specification with Tags { def is = args(exclude="slow")^
  "The Project Euler problems:"                                         ^ p^
  "If we list all the natural numbers below 10 that are multiples of 3 or 5, we get 3, 5, 6 and 9. The sum of these multiples is 23." ^
    "Find the sum of all the multiples of 3 or 5 below 1000."           ! e1^
                                                                        endp^
  "Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:" ^
    "1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ..."                            ^ bt^
    "By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms." ! e2^
                                                                        endp^
  "The prime factors of 13195 are 5, 7, 13 and 29." ^
    "What is the largest prime factor of the number 600851475143 ?"     ! e3^
                                                                        endp^
  "A palindromic number reads the same both ways. The largest palindrome made from the product of two 2-digit numbers is 9009 = 91 × 99." ^
    "Find the largest palindrome made from the product of two 3-digit numbers." ! e4^
                                                                        endp^
  "2520 is the smallest number that can be divided by each of the numbers from 1 to 10 without any remainder." ^
    "What is the smallest positive number that is evenly divisible by all of the numbers from 1 to 20?" ! e5^
                                                                        endp^
  "The sum of the squares of the first ten natural numbers is,"         ^
    "1^2 + 2^2 + ... + 10^2 = 385"                                      ^ bt^ bt^
  "The square of the sum of the first ten natural numbers is,"          ^
    "(1 + 2 + ... + 10)^2 = 55^2 = 3025"                                ^ bt^ bt^
  "Hence the difference between the sum of the squares of the first ten natural numbers and the square of the sum is 3025 − 385 = 2640." ^ bt^
    "Find the difference between the sum of the squares of the first one hundred natural numbers and the square of the sum." ! e6^
                                                                        endp^
  "By listing the first six prime numbers: 2, 3, 5, 7, 11, and 13, we can see that the 6th prime is 13." ^
    "What is the 10001st prime number?"                                 ! e7^
                                                                        endp^
  "Find the greatest product of five consecutive digits in the 1000-digit number." ^
    "731…450"                                                           ! e8^
                                                                        endp^
  "A Pythagorean triplet is a set of three natural numbers, a < b < c, for which," ^
    "a^2 + b^2 = c^2"                                                   ^ bt^ bt^
  "For example, 3^2 + 4^2 = 9 + 16 = 25 = 5^2."                         ^ p^
  "There exists exactly one Pythagorean triplet for which a + b + c = 1000." ^ bt^
    "Find the product abc."                                             ! e9^
                                                                        endp^
  "The sum of the primes below 10 is 2 + 3 + 5 + 7 = 17."               ^
    "Find the sum of all the primes below two million."                 ! e10^ tag("slow")^
                                                                        endp^
  "In the 20×20 grid below, four numbers along a diagonal line have been marked in red." ^ bt^
  "The product of these numbers is 26 × 63 × 78 × 14 = 1788696."        ^
  "What is the greatest product of four adjacent numbers in any direction (up, down, left, right, or diagonally) in the 20×20 grid?" ! e11 ^
                                                                        endp^
  "What is the value of the first triangle number to have over five hundred divisors?" ! e12^
                                                                        endp^
  "Work out the first ten digits of the sum of the following one-hundred 50-digit numbers." ! e13^
                                                                        end

  import Euler._

  def e1 = euler1 === 233168
  def e2 = euler2 === 4613732
  def e3 = euler3 === 6857
  def e4 = euler4 === 906609
  def e5 = euler5 === 232792560
  def e6 = euler6 === 25164150
  def e7 = euler7 === 104743
  def e8 = euler8 === 40824
  def e9 = euler9 === 31875000
  def e10 = euler10 === 142913828922L
  def e11 = euler11 === 70600674
  def e12 = euler12 === 76576500
  def e13 = euler13 === "5537376230"
}
